# Generated by Django 4.2.2 on 2023-06-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = []
